export const CATEGORIES = [
  "FOOD_AND_DRINK",
  "GENERAL_MERCHANDISE",
  "TRANSPORTATION",
  "TRAVEL",
  "ENTERTAINMENT",
  "RENT_AND_UTILITIES",
  "MEDICAL",
  "PERSONAL_CARE",
  "EDUCATION",
  "INCOME",
  "TRANSFER_IN",
  "TRANSFER_OUT",
  "LOAN_PAYMENTS",
  "BANK_FEES",
  "HOME_IMPROVEMENT",
  "GENERAL_SERVICES",
  "GOVERNMENT_AND_NON_PROFIT",
  "OTHER",
] as const;

export type Category = (typeof CATEGORIES)[number];
